### ISSUE TITLE
errors while compiling the code

### ISSUE THREAD

**Issue by Nityasagar** [Infant83/TBFIT#1]
I am getting the following errors while compiling the code. Could you kindly help me with this?

make
mpif90 -DMPI -O3  -c mpi_basics.f90
mpif90 -DMPI -O3  -c mpi_setup.f90
mpif90 -DMPI -O3  -c parameters.f90
parameters.f90:18.60:

  complex*16, public, dimension(2,2),   parameter :: pauli_0 = (/  1,  0,  0,
                                                            1
Error: Incompatible ranks 2 and 1 in assignment at (1)
parameters.f90:19.60:

  complex*16, public, dimension(2,2),   parameter :: pauli_x = (/  0,  1,  1,
                                                            1
Error: Incompatible ranks 2 and 1 in assignment at (1)
parameters.f90:20.60:

  complex*16, public, dimension(2,2),   parameter :: pauli_y = (/  0,  1, -1,
                                                            1
Error: Incompatible ranks 2 and 1 in assignment at (1)
parameters.f90:21.60:

  complex*16, public, dimension(2,2),   parameter :: pauli_z = (/  1,  0,  0, -
                                                            1
Error: Incompatible ranks 2 and 1 in assignment at (1)
parameters.f90:22.64:

  integer*4,  public, dimension(3,3,3), parameter :: levi_civita = (/0,0,0, 0,0
                                                                1
Error: Incompatible ranks 3 and 1 in assignment at (1)
parameters.f90:25.64:

  integer*4,  public, dimension(3,2),   parameter :: cyclic_axis = (/2,3,1,3,1,
                                                                1
Error: Incompatible ranks 2 and 1 in assignment at (1)
make: *** [parameters.o] Error 1
###################################################################
makefile used

# $^ : dependency list
# $@ : target

#OPTIONS= -fpp -DMPI -mcmodel=large # for curion2
OPTIONS=  -DMPI

#F90    = ifort -mkl $(OPTIONS)
#F90    = mpif90 -mkl $(OPTIONS)
F90    = mpif90 $(OPTIONS)
#FFLAG = -assume byterecl -O2
FFLAG  = -O3 # -heap-arrays -nogen-interfaces

MPI_MOD= mpi_basics.o mpi_setup.o
TEST   = test.o
MODULE = $(MPI_MOD) \
                 parameters.o read_incar.o orbital_wavefunction.o \
                 kronecker_prod.o phase_factor.o do_math.o \
         sorting.o berry_phase.o
READER = read_input.o read_param.o read_poscar.o read_kpoint.o \
                 read_energy.o set_weight.o get_site_number.o find_nn.o
WRITER = plot_eigen_state.o plot_stm_image.o set_ribbon_geom.o print_energy.o \
                 print_wcc.o print_zak_phase.o print_berry_curvature.o
GET    = get_tij.o get_eig.o get_dos.o get_soc.o get_param_class.o \
                 get_cc_param.o get_berry_curvature.o get_wcc.o get_zak_phase.o \
         get_z2_invariant.o
MINPACK_LIB= get_fit.o minpack_sub.o lmdif.o
#MKLPATH= $(MKLROOT)
#LAPACK = -L$(MKLPATH)/lib/ \
         -lmkl_intel_lp64 -lmkl_sequential \
         -lmkl_core -liomp5
MKLPATH = /opt/intel/mkl/lib/intel64
LAPACK = -L$(MKLPATH) -lmkl_core -lmkl_intel_lp64 -lmkl_sequential -lpthread -liomp5

OBJECTS=$(MODULE) tbfit.o tbpack.o $(READER) $(WRITER) $(GET) e_onsite.o $(MINPACK_LIB) $(TEST)
BIN=~/code/bin

#########################################

$(BIN)/tbfit: $(OBJECTS)
        $(F90) -o $@ $^ $(LAPACK)

.SUFFIXES: .f .f90 #.mod
%.o: %.f
        $(F90) $(FFLAG) -c $<
%.o: %.f90
        $(F90) $(FFLAG) -c $<
clean:
        rm $(BIN)/tbfit $(OBJECTS) *.mod

**Comment by Infant83** [comment]
Dear Nityasagar,

This is originated from the array declaration in parameter.f90.
I have modified the source code parameter.f90, so please download updated file again and try to recompile it.

Cheers,
Hyun-Jung.

**Comment by Infant83** [comment]
Dear Nityasagar,

This is originated from the array declaration in parameter.f90.
I have modified the source code parameter.f90, so please download updated file again and try to recompile it.

Cheers,
Hyun-Jung.


------------------------------------------------------------------------
Hyun-Jung Kim, Ph. D. (Research Fellow)
Rm 1534, School of Computational Sciences, 
Korea Institute for Advance Study (KIAS)
Hoegiro 85, Dongdaemun-gu, Seoul 02455, Korea
------------------------------------------------------------------------
tel : +82 2 958 2534
mobile : +82 10 7335 7889
publication list: google.scholar <https://scholar.google.com/citations?user=FtSLeT4AAAAJ&hl=en>
------------------------------------------------------------------------

**Comment by nityasagarjena** [comment]
Dear Hyun-Jung,
 Thanks for your immediate reply. I have used the recently undated one but encountered with the following errors. Could you kindly have a look to the bellow appended text?

make
mpif90 -DMPI -O3  -c read_incar.f90
Warning: read_incar.f90:1: Illegal preprocessor directive
read_incar.f90:43.18:

                  if_main write(6,'(A,*(I6))')' EIG_PLOT:  ',PINPT%i_eig_print
                  1
Error: Unclassifiable statement at (1)
read_incar.f90:50.18:

                  if_main write(6,'(A,*(I6))')' KPT_PLOT:  ',PINPT%i_kpt_print
                  1
Error: Unclassifiable statement at (1)
read_incar.f90:59.20:

                    if_main write(6,'(A)')'    !WARN! NGRID tag of "SET EIGPLOT
                    1
Error: Unclassifiable statement at (1)
read_incar.f90:60.20:

                    if_main write(6,'(A,A)')'           Please check NGRID tag
                    1
Error: Unclassifiable statement at (1)
read_incar.f90:68.20:

                    if_main  write(6,'(A,3(F15.8))')'   R_ORIG:  ',PINPT%r_orig
                    1
Error: Unclassifiable statement at (1)
read_incar.f90:71.20:

                    if_main write(6,'(A)')'    !WARN! RORIGIN tag of "SET EIGPL
                    1
Error: Unclassifiable statement at (1)
read_incar.f90:72.20:

                    if_main write(6,'(A,A)')'           Please check RORIGIN ta
                    1
Error: Unclassifiable statement at (1)
read_incar.f90:80.20:

                    if_main write(6,'(A,L)')' WAV_PLOT:  ',PINPT%flag_plot_wave
                    1
Error: Unclassifiable statement at (1)
read_incar.f90:82.20:

                    if_main write(6,'(A)')'    !WARN! WAV_PLOT tag of "SET EIGP
                    1
Error: Unclassifiable statement at (1)
read_incar.f90:83.20:

                    if_main write(6,'(A,A)')'           Please check WAV_PLOT t
                    1
Error: Unclassifiable statement at (1)
read_incar.f90:91.20:

                    if_main write(6,'(A,F9.4)')' RCUT_ORB:  ',PINPT%rcut_orb_pl
                    1
Error: Unclassifiable statement at (1)
read_incar.f90:93.20:

                    if_main write(6,'(A)')'    !WARN! RCUT_ORB tag of "SET EIGP
                    1
Error: Unclassifiable statement at (1)
read_incar.f90:94.20:

                    if_main write(6,'(A,A)')'           Please check RCUT_ORB t
                    1
Error: Unclassifiable statement at (1)
read_incar.f90:105.12:

            if_main write(6,'(A,L)')' STM_PLOT:  ',PINPT%flag_plot_stm_image
            1
Error: Unclassifiable statement at (1)
read_incar.f90:122.20:

                    if_main write(6,'(A)')'    !WARN! NGRID tag of "SET STMPLOT
                    1
Error: Unclassifiable statement at (1)
read_incar.f90:123.20:

                    if_main write(6,'(A,A)')'           Please check NGRID tag
                    1
Error: Unclassifiable statement at (1)
read_incar.f90:136.22:

                      if_main write(6,'(A,I2,A,F9.4,A,F9.4,A)')' STM_ERAN: PLOT
                      1
Error: Unclassifiable statement at (1)
read_incar.f90:139.22:

                      if_main write(6,'(A)')'    !WARNING!  STM_ERANGE is not p
                      1
Error: Unclassifiable statement at (1)
read_incar.f90:140.22:

                      if_main write(6,'(A)')'    !WARNING!  Proper usage is as
                      1
Error: Unclassifiable statement at (1)
read_incar.f90:141.22:

                      if_main write(6,'(A)')'    !WARNING!    STM_ERANGE  EMIN:
                      1
Error: Unclassifiable statement at (1)
read_incar.f90:142.22:

                      if_main write(6,'(A)')'    !WARNING!  Exit program...'
                      1
Error: Unclassifiable statement at (1)
read_incar.f90:150.20:

                    if_main write(6,'(A,I2,A,F9.4,A,F9.4,A)')' STM_ERAN: PLOT('
                    1
Error: Unclassifiable statement at (1)
read_incar.f90:158.20:

                    if_main write(6,'(A,F9.4)')' RCUT_ORB:  ',PINPT%rcut_orb_pl
                    1
Error: Unclassifiable statement at (1)
read_incar.f90:160.20:

                    if_main write(6,'(A)')'    !WARN! RCUT_ORB tag of "SET EIGP
                    1
Error: Unclassifiable statement at (1)
read_incar.f90:161.20:

                    if_main write(6,'(A,A)')'           Please check RCUT_ORB t
                    1
Error: Unclassifiable statement at (1)
Fatal Error: Error count reached limit of 25.
make: *** [read_incar.o] Error 1

**Comment by Infant83** [comment]
Dear Nitya,

Please add -fpp option in OPTION tag of your makefile

OPTIONS= -fpp -DMPI

Sincerely,
Hyun-Jung.


------------------------------------------------------------------------
Hyun-Jung Kim, Ph. D. (Research Fellow)
Rm 1534, School of Computational Sciences, 
Korea Institute for Advance Study (KIAS)
Hoegiro 85, Dongdaemun-gu, Seoul 02455, Korea
------------------------------------------------------------------------
tel : +82 2 958 2534
mobile : +82 10 7335 7889
publication list: google.scholar <https://scholar.google.com/citations?user=FtSLeT4AAAAJ&hl=en>
------------------------------------------------------------------------
