### ISSUE TITLE
Can't finish installation

### ISSUE THREAD

**Issue by perrychen0417** [Infant83/TBFIT#2]
Hello,

When I installed the tbfit code, I faced a question. I gave command "make tbfit" as the manual says.  I went to TBFIT-master folder and typed 'make tbfit'. While the system tells me: 
No rule to make target '/include/mkl_spblas.f90', needed by 'mkl_spblas.o'.  Stop.

I think I didn't finish installation because when I went to the SOC folder and  input "tbfit < /dev/null | tee log.out", I got "Command 'tbfit' not found, did you mean:".

I want to ask whether I need to download mkl_spblas.f90? Or whether I have to change any route in the makefile? I still can't realize anything wrong in my step.

I think TBFIT will be a very good tool for me if I can success in installing. Thank you for your providing code.

**Comment by Infant83** [comment]
If you put -DMKL_SPARSE option in your OPTION tag of makefile, you need to make sure that the 
mkl_spblas.f90 is exist in $(MKLPATH)/include/mkl_spblas.f90

Please check your MKL version. If available, please use recent MKL distributions.

If you don't need to work with sparse matrix eigensolver, 
then just remove -DMKL_SPARSE option. The installation problem will be gone away, but 
some features will be restricted.

Thank you.
