### ISSUE TITLE
Bug in the Makefile

### ISSUE THREAD

**Issue by shahramyalameha** [Infant83/TBFIT#6]
Hi, 
I think in the latest version **get_unfold.o** module is not addressed in the **Makefile**.
When installing this code, I encounter an error because this module does not exist!
Thank you.

Shahram.

**Comment by Infant83** [comment]
Oh. Thank you very much for pointing out the mistake. 
I've changed the makefile now and it would be working. 
Note that the unfolding functionality is under development so nothing is available with these functions. 

Hyun-Jung

**Comment by shahramyalameha** [comment]
Yes, the code was installed well with this change.
thank you

Shahram
